//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleTracking.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeValue
    {
        public int AttributeValueID { get; set; }
        public int AttributeID { get; set; }
        public int TrackingID { get; set; }
        public string Value { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Tracking Tracking { get; set; }
    }
}
